/**
 * Generate a deployable MCP server package from a world model.
 * Creates package.json, server.ts, and config snippets.
 */

import type { WorldModelType } from "../schema/index.js";

export interface McpPackageFiles {
  "package.json": string;
  "server.ts": string;
  "model.json": string;
  "README.md": string;
  "claude-config.json": string;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Generate all files needed for a standalone MCP server package.
 */
export function generateMcpPackage(
  model: WorldModelType,
  options?: { name?: string; port?: number },
): McpPackageFiles {
  const name = options?.name ?? slugify(model.name);
  const displayName = model.name;
  const entityCount = model.entities.length;
  const toolCount = 9;

  const packageJson = JSON.stringify(
    {
      name: `swm-mcp-${name}`,
      version: model.version ?? "1.0.0",
      description: `MCP server for ${displayName} — ${entityCount} entities, ${toolCount} queryable tools`,
      type: "module",
      main: "server.ts",
      scripts: {
        start: "npx tsx server.ts",
        dev: "npx tsx --watch server.ts",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.29.0",
        zod: "^4.3.6",
        tsx: "^4.21.0",
      },
    },
    null,
    2,
  );

  const serverTs = `#!/usr/bin/env npx tsx
/**
 * MCP Server: ${displayName}
 * ${model.description}
 *
 * ${entityCount} entities, ${model.relations.length} relations, ${model.processes.length} processes
 * Generated by Structured World Model
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const model = JSON.parse(readFileSync(resolve(import.meta.dirname, "model.json"), "utf-8"));
const entityNames = model.entities.map((e: any) => e.name);

const server = new McpServer({
  name: "swm-${name}",
  version: model.version ?? "1.0.0",
});

const findEntity = (name: string) =>
  model.entities.find((e: any) => e.name.toLowerCase() === name.toLowerCase()) ??
  model.entities.find((e: any) => e.name.toLowerCase().includes(name.toLowerCase()));

server.tool("get_entity", "Look up a domain entity", { name: z.string() }, async ({ name }) => {
  const entity = findEntity(name);
  if (!entity) return { content: [{ type: "text", text: \`Entity "\${name}" not found. Available: \${entityNames.join(", ")}\` }] };
  return { content: [{ type: "text", text: \`**\${entity.name}** (\${entity.type})\\n\${entity.description}\` }] };
});

server.tool("get_stats", "Model statistics", {}, async () => {
  return { content: [{ type: "text", text: \`\${model.name}: \${model.entities.length} entities, \${model.relations.length} relations, \${model.processes.length} processes, \${model.constraints.length} constraints\` }] };
});

server.tool("search", "Search across all elements", { query: z.string() }, async ({ query }) => {
  const q = query.toLowerCase();
  const matches = model.entities.filter((e: any) => e.name.toLowerCase().includes(q) || e.description.toLowerCase().includes(q));
  return { content: [{ type: "text", text: matches.length ? matches.map((e: any) => \`**\${e.name}** (\${e.type}): \${e.description}\`).join("\\n") : "No matches." }] };
});

const transport = new StdioServerTransport();
await server.connect(transport);
`;

  const modelJson = JSON.stringify(model, null, 2);

  const readme = `# ${displayName} MCP Server

${model.description}

## Quick Start

\`\`\`bash
npm install
npm start
\`\`\`

## Stats

- **${entityCount}** entities
- **${model.relations.length}** relations
- **${model.processes.length}** processes
- **${model.constraints.length}** constraints

## Tools

| Tool | Description |
|------|-------------|
| get_entity | Look up any domain entity by name |
| get_stats | Model statistics overview |
| search | Full-text search across all elements |

## Configuration

Add to your Claude Desktop or VS Code MCP config:

\`\`\`json
${JSON.stringify({ mcpServers: { [name]: { command: "npx", args: ["tsx", "server.ts"], cwd: "." } } }, null, 2)}
\`\`\`

Generated by [Structured World Model](https://github.com/alexrozex/structured-world-model)
`;

  const claudeConfig = JSON.stringify(
    {
      mcpServers: {
        [name]: {
          command: "npx",
          args: ["tsx", "server.ts"],
          cwd: `./${name}`,
        },
      },
    },
    null,
    2,
  );

  return {
    "package.json": packageJson,
    "server.ts": serverTs,
    "model.json": modelJson,
    "README.md": readme,
    "claude-config.json": claudeConfig,
  };
}
