/**
 * Summary card — a concise, copy-pasteable overview of a world model.
 * Designed for Slack, PRs, READMEs, and quick sharing.
 */

import type { WorldModelType } from "../schema/index.js";

/**
 * Generate a concise summary card for a world model.
 * ~20-30 lines, markdown formatted, designed for pasting.
 */
export function toSummaryCard(model: WorldModelType): string {
  const lines: string[] = [];

  // Header
  lines.push(`## ${model.name}`);
  lines.push("");
  lines.push(model.description);
  lines.push("");

  // Key numbers
  const stats = [
    `${model.entities.length} entities`,
    `${model.relations.length} relations`,
    `${model.processes.length} processes`,
    `${model.constraints.length} constraints`,
  ].join(" · ");
  lines.push(`> ${stats}`);
  if (model.metadata?.confidence !== undefined) {
    lines.push(`> Confidence: ${Math.round(model.metadata.confidence * 100)}%`);
  }
  lines.push("");

  // Entity types breakdown
  const byType = new Map<string, string[]>();
  for (const e of model.entities) {
    const list = byType.get(e.type) ?? [];
    list.push(e.name);
    byType.set(e.type, list);
  }
  lines.push("**Entities:**");
  for (const [type, names] of byType) {
    lines.push(`- **${type}:** ${names.join(", ")}`);
  }
  lines.push("");

  // Key relationships (top 5 by most connected entities)
  if (model.relations.length > 0) {
    const entityName = (id: string) =>
      model.entities.find((e) => e.id === id)?.name ?? id;
    const topRels = model.relations.slice(0, 5);
    lines.push("**Key Relationships:**");
    for (const r of topRels) {
      lines.push(
        `- ${entityName(r.source)} → *${r.type}* → ${entityName(r.target)}`,
      );
    }
    if (model.relations.length > 5) {
      lines.push(`- *...and ${model.relations.length - 5} more*`);
    }
    lines.push("");
  }

  // Processes
  if (model.processes.length > 0) {
    lines.push("**Processes:**");
    for (const p of model.processes) {
      lines.push(
        `- **${p.name}:** ${p.description.slice(0, 80)}${p.description.length > 80 ? "..." : ""}`,
      );
    }
    lines.push("");
  }

  // Hard constraints
  const hardConstraints = model.constraints.filter(
    (c) => c.severity === "hard",
  );
  if (hardConstraints.length > 0) {
    lines.push("**Constraints:**");
    for (const c of hardConstraints) {
      lines.push(
        `- 🔒 ${c.name}: ${c.description.slice(0, 60)}${c.description.length > 60 ? "..." : ""}`,
      );
    }
    lines.push("");
  }

  // Footer
  lines.push(
    `*v${model.version} · ${model.entities.length} entities · generated by SWM*`,
  );

  return lines.join("\n");
}
