import type { BuildContract, FileTreeNode } from "@swm/compiler";

// ─── BUILD.md Generator ───────────────────────────────────────────────────────
// Produces a deterministic BUILD.md from the BLD stage BuildContract.
// This file is Claude Code's build contract — read it before touching a file.

function renderFileTree(nodes: readonly FileTreeNode[]): string {
  // Group by top-level directory for readability
  const byDir = new Map<string, FileTreeNode[]>();
  for (const node of nodes) {
    const top = node.path.split("/")[0]!;
    if (!byDir.has(top)) byDir.set(top, []);
    byDir.get(top)!.push(node);
  }

  const lines: string[] = [];
  for (const [dir, dirNodes] of byDir) {
    // Sort: directories before files, then alphabetically
    const sorted = [...dirNodes].sort((a, b) => {
      if (a.type !== b.type) return a.type === "directory" ? -1 : 1;
      return a.path.localeCompare(b.path);
    });

    for (const node of sorted) {
      const indent = node.path.split("/").length - 1;
      const prefix = "  ".repeat(indent);
      const marker = node.type === "directory" ? "/" : "";
      const componentTag = node.componentName ? ` ← ${node.componentName}` : "";
      lines.push(
        `${prefix}${node.path.split("/").pop()}${marker}  # ${node.purpose}${componentTag}`,
      );
    }
    void dir;
  }
  return lines.join("\n");
}

function renderDependencies(contract: BuildContract): string {
  const allPackages = new Set<string>();
  const allDevPackages = new Set<string>();

  for (const spec of contract.dependencies) {
    for (const pkg of spec.packages) allPackages.add(pkg);
    for (const pkg of spec.devPackages) allDevPackages.add(pkg);
  }

  const lines: string[] = [];
  if (allPackages.size > 0) {
    lines.push("**dependencies:**");
    for (const pkg of [...allPackages].sort()) {
      lines.push(`- \`${pkg}\``);
    }
  }
  if (allDevPackages.size > 0) {
    lines.push("");
    lines.push("**devDependencies:**");
    for (const pkg of [...allDevPackages].sort()) {
      lines.push(`- \`${pkg}\``);
    }
  }
  return lines.join("\n");
}

function renderAcceptanceCriteria(contract: BuildContract): string {
  return contract.acceptanceCriteria
    .map((ac) => `- **${ac.boundedContext}:** ${ac.criterion}`)
    .join("\n");
}

export function buildContractToBuildMD(contract: BuildContract): string {
  const sections: string[] = [];

  sections.push(`# BUILD.md`);
  sections.push(
    `> Generated by Ada BLD stage. Do not edit manually — re-run \`ada compile --amend\` to update.`,
  );
  sections.push("");

  // Stack
  sections.push(`## Stack`);
  sections.push(`**${contract.stackLabel}**`);
  sections.push(
    `> All implementation decisions must use this stack. Do not introduce alternative frameworks.`,
  );
  sections.push("");

  // Acceptance Criteria — first, most important
  sections.push(`## Acceptance Criteria`);
  sections.push(`The build is complete when all of the following hold:`);
  sections.push("");
  sections.push(renderAcceptanceCriteria(contract));
  sections.push("");

  // File Tree
  sections.push(`## File Tree`);
  sections.push(
    `Create exactly these files. Do not create files outside this tree without explicit instruction.`,
  );
  sections.push("");
  sections.push("```");
  sections.push(renderFileTree(contract.fileTree));
  sections.push("```");
  sections.push("");

  // Dependencies
  sections.push(`## Dependencies`);
  sections.push(
    `Install exactly these packages. Do not add unlisted packages.`,
  );
  sections.push("");
  sections.push(renderDependencies(contract));
  sections.push("");

  // Provenance
  sections.push(`## Provenance`);
  sections.push(`Stack: \`${contract.stack}\`  `);
  sections.push(`Gate: ${contract.gatePass ? "PASS" : "FAIL"}  `);
  sections.push(`Postcode: \`${contract.postcode.raw}\``);

  return sections.join("\n");
}
